<a href="https://colab.research.google.com/github/akkybm/Tensorflow/blob/main/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **TENSORFLOW Basics**



In [3]:
import tensorflow as tf

In [4]:
#Tensor Objects

In [5]:
hello = tf.constant('Hello World!')

In [6]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [7]:
x = tf.constant(100)

In [8]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [9]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [10]:
#SESSIONS

In [12]:
tf.compat.v1.disable_eager_execution()

In [13]:
sess = tf.compat.v1.Session()

In [17]:
print(hello)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [18]:
print(x)

tf.Tensor(100, shape=(), dtype=int32)


In [19]:
#OPERATIONS

In [20]:
x = tf.constant(2)
y = tf.constant(3)

In [22]:
z = tf.multiply(x,y)

In [24]:
result = sess.run(z)

In [25]:
print(result)

6


In [26]:
print('Addition: ', sess.run(x+y))

Addition:  5


In [27]:
print('Multiplication: ', sess.run(x*y))

Multiplication:  6


In [28]:
print('Division: ', sess.run(x/y))

Division:  0.6666666666666666


In [29]:
import numpy as np

In [30]:
a = np.array([[5.0,5.0]])

In [32]:
b = np.array([[2.0],[2.0]])

In [33]:
a

array([[5., 5.]])

In [34]:
b

array([[2.],
       [2.]])

In [35]:
mat1 = tf.constant(a)

In [36]:
mat2 = tf.constant(b)

In [37]:
mat_multiply = tf.matmul(mat1,mat2)

In [38]:
sess.run(mat_multiply)

array([[20.]])